Add equality_comparable concept for ASSERT_EQ (#15)
Previously, ASSERT_EQ required both values passed to be the same type.

It's now templated on two types, so this snippet works:

size_t x = 1;
int y = 1;
ASSERT_EQ(x, y);
We introduce concepts to help with error messages. If you pass a std::string and a size_t, for example, you now see

..\Test\test_utest.cpp(148): error C2672: 'testlib::test::AssertEqImpl': no matching overloaded function found
..\Src\unittest.h(73): note: could be 'void testlib::test::AssertEqImpl(const char *,const char *,int,const char *,bool,T,U)'
..\Test\test_utest.cpp(148): note: the associated constraints are not satisfied
..\Src\unittest.h(72): note: the concept 'std::equality_comparable_with<size_t,std::string>' evaluated to false
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\concepts(212): note: the concept 'std::_Comparison_common_type_with<size_t,std::string>' evaluated to false
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\concepts(205): note: 'std::_Comparison_common_type_with_impl': too few template arguments
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\concepts(199): note: see declaration of 'std::_Comparison_common_type_with_impl'
unittest.cpp